/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.ProveedorController;
import controller.RegistroCompraController;
import controller.TipoCambioController;
import entity.Proveedor;
import entity.RegistroCompra;
import entity.TipoCambio;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCRODINPC-05
 */

public class CuentasPorPagar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuentasPorCobrar
     */
    String filtro="p.razonSocial";
    
    float cambioVenta;
    
    ProveedorController proveedorcontroler= new ProveedorController();
    Proveedor proveedor;
    
    public CuentasPorPagar() {
        initComponents();
        listaComprasPagar(filtro, txtLike.getText());
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLike = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonReporteVencidos = new javax.swing.JButton();
        buttonImprimirReporte = new javax.swing.JButton();
        buttonRegistroVenta = new javax.swing.JButton();
        buttonCerrar = new javax.swing.JButton();
        buttonLimpiarTabla = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        buttonVistaTotal = new javax.swing.JButton();
        buttonVistaVencidos = new javax.swing.JButton();
        buttonLimpiarInformacion = new javax.swing.JButton();
        txtRazSocialReport = new javax.swing.JTextField();
        buttonReporteTotal = new javax.swing.JButton();
        buttonImprimirTotal = new javax.swing.JButton();
        labelComprobante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumCotizacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cuentas por cobrar");

        txtLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLikeActionPerformed(evt);
            }
        });
        txtLike.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLikeKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProveedor", "Razón Social", "R.U.C.", "Monto Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(530);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "RAZÓN SOCIAL", "FACTURA" }));
        comboBoxFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxFiltroItemStateChanged(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idRCompra", "Comprobante", "F. Emisión", "Monto $", "Monto S/", "F. Vencimiento", "Deuda", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(7).setPreferredWidth(220);
        }

        buttonReporteVencidos.setText("Reporte Vencidos");
        buttonReporteVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReporteVencidosActionPerformed(evt);
            }
        });

        buttonImprimirReporte.setText("Imprimir Vencidos");
        buttonImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirReporteActionPerformed(evt);
            }
        });

        buttonRegistroVenta.setText("Ver Registro Compra");
        buttonRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistroVentaActionPerformed(evt);
            }
        });

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        buttonLimpiarTabla.setText("Limpiar");
        buttonLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarTablaActionPerformed(evt);
            }
        });

        jLabel16.setText("Todo comprobante para que no esté en la lista de cuentas por cobrar su estado debe ser \"CANCELADO\" o lo que usted considere. Para ver la lista de Estado, revisar la Vista de Compras.");

        buttonVistaTotal.setText("Vista Total Comprobantes");
        buttonVistaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVistaTotalActionPerformed(evt);
            }
        });

        buttonVistaVencidos.setText("Vista Comprobantes Vencidos");
        buttonVistaVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVistaVencidosActionPerformed(evt);
            }
        });

        buttonLimpiarInformacion.setText("Limpiar");
        buttonLimpiarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarInformacionActionPerformed(evt);
            }
        });

        buttonReporteTotal.setText("Reporte Total");
        buttonReporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReporteTotalActionPerformed(evt);
            }
        });

        buttonImprimirTotal.setText("Imprimir Total");
        buttonImprimirTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirTotalActionPerformed(evt);
            }
        });

        labelComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComprobante.setText("COMPROBANTE");

        jLabel2.setText("Serie:");

        jLabel3.setText("Número:");

        jLabel4.setText("N° Cot.:");

        jLabel5.setText("N° Pedido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(3, 3, 3)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addGap(2, 2, 2)
                                .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(buttonCerrar))
                            .addComponent(buttonRegistroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonReporteVencidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonReporteTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonImprimirTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLike, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpiarTabla))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRazSocialReport, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonVistaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonVistaVencidos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpiarInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpiarTabla)
                    .addComponent(txtLike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVistaTotal)
                    .addComponent(buttonVistaVencidos)
                    .addComponent(buttonLimpiarInformacion)
                    .addComponent(txtRazSocialReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelComprobante)
                            .addComponent(jLabel2)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonReporteTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReporteVencidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonImprimirTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImprimirReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRegistroVenta)
                        .addGap(23, 23, 23)
                        .addComponent(buttonCerrar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        
    }//GEN-LAST:event_buttonCerrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboBoxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFiltroItemStateChanged
        
    }//GEN-LAST:event_comboBoxFiltroItemStateChanged

    private void txtLikeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLikeKeyReleased
        
    }//GEN-LAST:event_txtLikeKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void buttonLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarTablaActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_buttonLimpiarTablaActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
       
    }//GEN-LAST:event_jTable1KeyReleased

    private void buttonReporteVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReporteVencidosActionPerformed
         
    }//GEN-LAST:event_buttonReporteVencidosActionPerformed

    private void buttonImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirReporteActionPerformed
        
    }//GEN-LAST:event_buttonImprimirReporteActionPerformed

    private void buttonRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistroVentaActionPerformed
        
    }//GEN-LAST:event_buttonRegistroVentaActionPerformed

    private void buttonVistaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVistaTotalActionPerformed
        
    }//GEN-LAST:event_buttonVistaTotalActionPerformed

    private void buttonVistaVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVistaVencidosActionPerformed
      
    }//GEN-LAST:event_buttonVistaVencidosActionPerformed

    private void buttonReporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReporteTotalActionPerformed
           
    }//GEN-LAST:event_buttonReporteTotalActionPerformed

    private void buttonImprimirTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirTotalActionPerformed
       
    }//GEN-LAST:event_buttonImprimirTotalActionPerformed

    private void buttonLimpiarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarInformacionActionPerformed
        limpiarInformacion();
    }//GEN-LAST:event_buttonLimpiarInformacionActionPerformed

    private void txtLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JButton buttonImprimirReporte;
    private javax.swing.JButton buttonImprimirTotal;
    private javax.swing.JButton buttonLimpiarInformacion;
    private javax.swing.JButton buttonLimpiarTabla;
    private javax.swing.JButton buttonRegistroVenta;
    private javax.swing.JButton buttonReporteTotal;
    private javax.swing.JButton buttonReporteVencidos;
    private javax.swing.JButton buttonVistaTotal;
    private javax.swing.JButton buttonVistaVencidos;
    private javax.swing.JComboBox<String> comboBoxFiltro;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelComprobante;
    private javax.swing.JTextField txtLike;
    private javax.swing.JTextField txtNumCotizacion;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRazSocialReport;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

 TipoCambioController tipocambiocontroler = new TipoCambioController();
 TipoCambio tipocambio;
 
 RegistroCompraController registrocompracontroler= new RegistroCompraController();
 RegistroCompra registrocompra;
 
 //--------------------------------------- Tabla 1 -----------------------------------------
    void listaComprasPagar(String nombreFiltro, String valorFiltro) {
        List<RegistroCompra> lista;
        try {
            lista = registrocompracontroler.RegistroCompraCuentasPagar(nombreFiltro, valorFiltro);
            verCompras(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    void verCompras(List<RegistroCompra> lista) throws Exception {
        
        DefaultTableModel tabla1 = (DefaultTableModel) jTable1.getModel();
        tabla1.setRowCount(0);
        for (RegistroCompra reco : lista) {
            
            Object[] fila = {reco.getIdProveedor_fk(), reco.getRazonSocial(), reco.getRuc(), reco.getSumaTotal()};
            tabla1.addRow(fila);
        }
    }
 
// ----------------------- CONSULTAR TIPO DE CAMBIO ------------------------------
 
 void consultarTipoCambio(String f) throws Exception {
        tipocambio =tipocambiocontroler.TipoCambioBuscarCambio(f) ;

        if (tipocambio != null) {
            cambioVenta=tipocambio.getPrecioVenta();
        } else {
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }
    }
 
 
//------------------------------------ Limpiar ---------------------------------
     
   void limpiarInformacion(){
       labelComprobante.setText("COMPROBANTE");
       txtSerie.setText("");
       txtNumero.setText("");
       txtNumCotizacion.setText("");
       txtNumPedido.setText("");
   }
   
   
   void limpiarTabla(){
       txtRazSocialReport.setText("");
       labelComprobante.setText("COMPROBANTE");
       txtSerie.setText("");
       txtNumero.setText("");
       txtNumCotizacion.setText("");
       txtNumPedido.setText("");   
   }
 
}
