/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.ArticuloProveedorController;
import controller.ContactoProveedorController;
import controller.DireccionAnexaProvController;
import controller.ProveedorArticuloController;
import controller.ProveedorController;
import entity.ArticuloProveedor;
import entity.ContactoProveedor;
import entity.DireccionAnexaProv;
import entity.Proveedor;
import entity.ProveedorArticulo;
import exportarexcel.clsExportarExcel;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCRODINPC-02
 */
public class ProveedoresVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProveedoresVista
     */
    String filtro="razonSocial";
    int tabla;
    int idProv;
    
//    ----------------------- SEGUNDA PESTAÑA -----------------------------
    String filtro2="ap.descripcion";
    int tabla2;
    int idProArt;
    int idProvee;
    int idArtPro;
    String preCom;
    String obs;
    String articulo;
    String prov;
    public ProveedoresVista() {
     initComponents();
     listaProveedorLike(filtro, txtbuscarRazonSocial.getText());
        
    // ---------------------- SEGUNDA PESTAÑA -------------------------
    
    listaProveedorArticulo(filtro2, txtFiltro.getText());
    habilitarInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        txtbuscarRazonSocial = new javax.swing.JTextField();
        buttonExportExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buttonNuevoProveedor = new javax.swing.JButton();
        buttonLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboBoxFiltro3 = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        buttonLimpiar2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProveedor3 = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        txtObs3 = new javax.swing.JTextField();
        buttonModificar3 = new javax.swing.JButton();
        buttonGuardar3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Vista de Proveedores");

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "RAZ. SOCIAL", "R.U.C." }));
        comboBoxFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxFiltroItemStateChanged(evt);
            }
        });

        txtbuscarRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarRazonSocialKeyReleased(evt);
            }
        });

        buttonExportExcel.setText("ExportExcel");
        buttonExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportExcelActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Razon Social", "R.U.C.", "Direccion", "Rubro", "Observacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(1).setMinWidth(0);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(330);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(10000);
            jTable1.getColumnModel().getColumn(2).setMinWidth(0);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(0);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(1000);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(1000);
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(1000);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idContProv", "Contacto", "Telefono1", "Correo", "Sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(117);
        }

        jLabel1.setText("Contactos:");

        jLabel2.setText("Direcciones Anexas:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idDirección", "Dirección", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(355);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(180);
        }

        buttonNuevoProveedor.setText("Nuevo Proveedor");
        buttonNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoProveedorActionPerformed(evt);
            }
        });

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(buttonExportExcel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscarRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExportExcel)
                    .addComponent(buttonNuevoProveedor)
                    .addComponent(buttonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedores", jPanel1);

        comboBoxFiltro3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PROVEEDOR", "ARTICULO/PRODUCTO" }));
        comboBoxFiltro3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxFiltro3ItemStateChanged(evt);
            }
        });

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        buttonLimpiar2.setText("Limpiar");
        buttonLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiar2ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProvArt", "Producto", "Proveedor", "Precio Compra", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jTable4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable4KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(350);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable4.getColumnModel().getColumn(4).setPreferredWidth(250);
        }

        jLabel3.setText("Proveedor:");

        jLabel4.setText("Producto:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Precio Compra:");

        jLabel6.setText("Observación:");

        buttonModificar3.setText("Modificar");
        buttonModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificar3ActionPerformed(evt);
            }
        });

        buttonGuardar3.setText("Guardar");
        buttonGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtObs3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonGuardar3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(buttonModificar3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModificar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtObs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGuardar3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Contactos:");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idContProv", "Contacto", "Telefono1", "Correo", "Sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable5.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable5.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable5.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTable5.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        jLabel8.setText("R.U.C.:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboBoxFiltro3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpiar2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxFiltro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonLimpiar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos/Servicios", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCerrar)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCerrarActionPerformed

    private void txtbuscarRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarRazonSocialKeyReleased
        listaProveedorLike(filtro, txtbuscarRazonSocial.getText());
    }//GEN-LAST:event_txtbuscarRazonSocialKeyReleased

    private void comboBoxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFiltroItemStateChanged
        if (comboBoxFiltro.getSelectedItem() == "RAZ. SOCIAL") {
            filtro = "razonSocial";
            listaProveedorLike(filtro, txtbuscarRazonSocial.getText());
            System.out.println(filtro);
        } else if (comboBoxFiltro.getSelectedItem() == "R.U.C.") {
            filtro = "ruc";
            listaProveedorLike(filtro, txtbuscarRazonSocial.getText());
            System.out.println(filtro);
        } else if (comboBoxFiltro.getSelectedItem() == "SELECCIONAR") {
            filtro = "razonSocial";
            listaProveedorLike(filtro, txtbuscarRazonSocial.getText());
            System.out.println(filtro);
        }
    }//GEN-LAST:event_comboBoxFiltroItemStateChanged

    private void buttonExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportExcelActionPerformed
        clsExportarExcel objeto = new clsExportarExcel();
        try {
            objeto.exportarExcel(jTable1);
        } catch (IOException ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonExportExcelActionPerformed

    private void buttonNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoProveedorActionPerformed
        Proveedores provs = null;
        try {
            provs = new Proveedores();
        } catch (Exception ex) {
            Logger.getLogger(ProveedoresVista.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal.jDesktopPane1.add(provs);
        provs.toFront();
        provs.setVisible(true);
    }//GEN-LAST:event_buttonNuevoProveedorActionPerformed

    private void comboBoxFiltro3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFiltro3ItemStateChanged
        //  TERCERA PESTAÑA / PESTAÑA PROVEEDORES POR ARTICULOS
        if (comboBoxFiltro3.getSelectedItem() == "PROVEEDOR") {
            filtro2 = "p.razonSocial";
            listaProveedorArticulo(filtro2, txtFiltro.getText());
            System.out.println(filtro2);
        } else if (comboBoxFiltro3.getSelectedItem() == "ARTICULO/PRODUCTO") {
            filtro2 = "ap.descripcion";
            listaProveedorArticulo(filtro2, txtFiltro.getText());
            System.out.println(filtro2);
        } else if (comboBoxFiltro3.getSelectedItem() == "SELECCIONAR") {
            filtro2 = "p.razonSocial";
            listaProveedorArticulo(filtro2, txtFiltro.getText());
            System.out.println(filtro2);
        }
    }//GEN-LAST:event_comboBoxFiltro3ItemStateChanged

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        //  TERCERA PESTAÑA / PESTAÑA PROVEEDORES POR ARTICULOS
        listaProveedorArticulo(filtro2, txtFiltro.getText());
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void buttonLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiar2ActionPerformed
        limpiar3();
        habilitarInicio();
    }//GEN-LAST:event_buttonLimpiar2ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        //  SEGUNDA PESTAÑA
        limpiar3();
        tabla2 = jTable4.getSelectedRow();
        idProArt = Integer.parseInt(jTable4.getValueAt(tabla2, 0).toString());

        
        try {
            consultarProveedorArticulo(idProArt);
        } catch (Exception ex) {
            Logger.getLogger(ProveedoresVista.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable4KeyReleased
        //  SEGUNDA PESTAÑA
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            limpiar3();
            tabla2 = jTable4.getSelectedRow();
            idProArt = Integer.parseInt(jTable4.getValueAt(tabla2, 0).toString());

         
            try {
                consultarProveedorArticulo(idProArt);
            } catch (Exception ex) {
                Logger.getLogger(ProveedoresVista.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jTable4KeyReleased

    private void buttonModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificar3ActionPerformed
        habilitarModificar3();
    }//GEN-LAST:event_buttonModificar3ActionPerformed

    private void buttonGuardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardar3ActionPerformed
        //  SEGUNDA PESTAÑA
        procesar3(2);
        listaProveedorArticulo(filtro2, txtFiltro.getText());
        habilitarInicio();
    }//GEN-LAST:event_buttonGuardar3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         limpiar();
         tabla = jTable1.getSelectedRow();
         idProv=Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());
         
         listaContactoProveedor(idProv);
         listaDireccionAnexaProv(idProv);
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
         if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            limpiar();
            tabla = jTable1.getSelectedRow();
            idProv = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());

            listaContactoProveedor(idProv);
            listaDireccionAnexaProv(idProv);
        }
    }//GEN-LAST:event_jTable1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JButton buttonExportExcel;
    private javax.swing.JButton buttonGuardar3;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonLimpiar2;
    private javax.swing.JButton buttonModificar3;
    private javax.swing.JButton buttonNuevoProveedor;
    private javax.swing.JComboBox<String> comboBoxFiltro;
    private javax.swing.JComboBox<String> comboBoxFiltro3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtObs3;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtProveedor3;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtbuscarRazonSocial;
    // End of variables declaration//GEN-END:variables

    ProveedorController obj = new ProveedorController();
    Proveedor proveedor;
    
    ContactoProveedorController contactocontroler = new ContactoProveedorController();
    ContactoProveedor contacto;
    
    ArticuloProveedorController articuloproveedorcontroler = new ArticuloProveedorController();
    ArticuloProveedor articuloproveedor;
    
    ProveedorArticuloController proveedorarticulocontroler = new ProveedorArticuloController();
    ProveedorArticulo proveedorarticulo;
    
    DireccionAnexaProvController direccionprovcontroler= new DireccionAnexaProvController();
    DireccionAnexaProv direccionprov;

    private void listaProveedor() {
        List<Proveedor> lista;
        try {
            lista = obj.ProveedorListar();
            verProveedor(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verProveedor(List<Proveedor> lista) {

        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        tabla.setRowCount(0);
        for (Proveedor pro : lista) {
            Object[] fila = {pro.getIdProveedor(), pro.getRazonSocial(), pro.getRuc(), pro.getDireccion(), pro.getRubro(), pro.getObservacion()};
            tabla.addRow(fila);
        }
    }

    private void listaProveedorLike(String filtro, String like) {
        List<Proveedor> lista;
        try {
            lista = obj.ProveedorFiltrar(filtro, like);
            verProveedor(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }
    
 
    //-------------------------------------- SEGUNDA PESTAÑA  -------------------------------------
     
     //------------------------------- Tabla-----------------------------

    private void listaProveedorArticulo(String filtrar, String pal) {
        List<ProveedorArticulo> lista;
        try {
            lista = proveedorarticulocontroler.ProveedorArticuloFiltrar(filtrar,pal);
            verProveedorArticulo(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verProveedorArticulo(List<ProveedorArticulo> lista) {
        DefaultTableModel tabla = (DefaultTableModel) jTable4.getModel();
        tabla.setRowCount(0);
        for (ProveedorArticulo proArt : lista) {
            
            Object[] fila = {proArt.getIdProvArtPk(),proArt.getArticulo(), proArt.getRazSocial(), 
                             proArt.getPrecio(), proArt.getObs() };
            tabla.addRow(fila);
        }
    }
    
    
    //---------------------------- Consultar --------------------------------------------
    
     private void consultarProveedorArticulo(int id ) throws Exception {
         proveedorarticulo= proveedorarticulocontroler.ProveedorArticuloBuscar(id);
        if (proveedorarticulo!= null) {
            
            idProArt = proveedorarticulo.getIdProvArtPk();
            idProvee = proveedorarticulo.getIdProv();
            listaContactoProveedorSegundaPestania(proveedorarticulo.getIdProv());
            consultarProveedorParaArticulo(proveedorarticulo.getIdProv());
            idArtPro = proveedorarticulo.getIdArtProv();
            consultarArticulo(idArtPro);
            preCom = proveedorarticulo.getPrecio();
            txtPrecioCompra.setText(proveedorarticulo.getPrecio()); 
            obs = proveedorarticulo.getObs();
            txtObs3.setText(proveedorarticulo.getObs());
 
            } else {
            JOptionPane.showMessageDialog(null, "Articulo no registrado");
            //System.out.println("Error");
        }
    }
     
     private void consultarProveedorParaArticulo(int id ) throws Exception {
        proveedor = obj.ProveedorBuscarId(id);
        if (proveedor!= null) {

            prov=proveedor.getRazonSocial();
            txtProveedor3.setText(prov);
            txtRucProveedor.setText(proveedor.getRuc());
            
        } else {
            JOptionPane.showMessageDialog(null, "Proveedor no registrado");
            //System.out.println("Error");
        }
    }
     
     private void consultarArticulo(int id ) throws Exception {
        articuloproveedor = articuloproveedorcontroler.ArticuloProveedorBuscar(id);
        if (articuloproveedor!= null) {

            articulo=articuloproveedor.getDescripcion();
            txtArticulo.setText(articuloproveedor.getDescripcion());
        } else {
            JOptionPane.showMessageDialog(null, "Articulo no registrado");
            //System.out.println("Error");
        }
    }
  
  //---------------------------- Procesar ----------------------------------------
    private void procesar3(int op) {

        proveedorarticulo = leerDatos3();

        try {

            String msg = proveedorarticulocontroler.ProveedorArticuloProcesar(proveedorarticulo, op);
            JOptionPane.showMessageDialog(null, msg);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Error" + e.getMessage());
        }
    }
    
     private ProveedorArticulo leerDatos3() {
        ProveedorArticulo proArt = new ProveedorArticulo();
        
        proArt.setIdProvArtPk(idProArt);
        proArt.setIdProv(idProvee);
        proArt.setIdArtProv(idArtPro);
        proArt.setPrecio(txtPrecioCompra.getText());
        proArt.setObs(txtObs3.getText());
           
        return proArt;
    }
     
     void habilitarInicio(){ 
        buttonLimpiar2.setEnabled(true);
        buttonModificar3.setEnabled(true);
        buttonGuardar3.setEnabled(false);

        txtFiltro.setEnabled(true);
        txtProveedor3.setEnabled(true);
        txtArticulo.setEnabled(true);
        txtPrecioCompra.setEnabled(false);
        txtObs3.setEnabled(false);
    }
    
    void habilitarModificar3() {
        buttonModificar3.setEnabled(false);
        buttonGuardar3.setEnabled(true);

        txtPrecioCompra.setEnabled(true);
        txtObs3.setEnabled(true);
    }
     
    void limpiar3() {
        txtFiltro.setText("");
        txtProveedor3.setText("");
        txtArticulo.setText("");
        txtPrecioCompra.setText("");
        txtObs3.setText("");
        txtRucProveedor.setText("");
        idProvee=0;
        listaContactoProveedorSegundaPestania(0);
    }
    
    
    //---------------------- TABLA DIRECCIÓN ANEXA -----------------------
    
    private void listaDireccionAnexaProv(int id) {
        List<DireccionAnexaProv> lista;
        try {
            lista =direccionprovcontroler.DireccionAnexaProvListar(id) ;
            verDireccionAnexa(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

     private void verDireccionAnexa(List<DireccionAnexaProv> lista) {
        DefaultTableModel tabla = (DefaultTableModel) jTable3.getModel();
        tabla.setRowCount(0);
        for (DireccionAnexaProv direc : lista) {
            
            Object[] fila = {direc.getIdDirAnexa(), direc.getDirec(), direc.getObs()};
            tabla.addRow(fila);
        }
    }
     
  //--------------------------- TABLA CONTACTOS PROVEEDOR -----------------------
     
     private void listaContactoProveedor(int idP) {
        List<ContactoProveedor> lista;
        try {
            lista = contactocontroler.ContactoProveedorListar1(idP);
            verOrdenCorte(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verOrdenCorte(List<ContactoProveedor> lista) {
        DefaultTableModel tabla = (DefaultTableModel) jTable2.getModel();
        tabla.setRowCount(0);
        for (ContactoProveedor conPro : lista) {
            
            Object[] fila = {conPro.getIdContactoProveedor(), conPro.getNombres()+" "+conPro.getApellidos() , 
                                conPro.getTlf1(), conPro.getCorreo(),conPro.getSucursal()};
            tabla.addRow(fila);
        }
    }
    
   //--------------------------- TABLA CONTACTOS PROVEEDOR  SEGUNDA PESTAÑA -----------------------
     
     private void listaContactoProveedorSegundaPestania(int idP1) {
         System.out.println("TABLA DE CONTACTO PROVEEDOR");
        List<ContactoProveedor> lista;
        try {
            lista = contactocontroler.ContactoProveedorListar1(idP1);
            verOrdenCorteSegundaPestania(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verOrdenCorteSegundaPestania(List<ContactoProveedor> lista) {
        System.out.println("TABLA DE CONTACTO PROVEEDOR 222222222222222");
        DefaultTableModel tabla = (DefaultTableModel) jTable5.getModel();
        tabla.setRowCount(0);
        for (ContactoProveedor conPro : lista) {
            
            Object[] fila = {conPro.getIdContactoProveedor(), conPro.getNombres()+" "+conPro.getApellidos() , 
                                conPro.getTlf1(), conPro.getCorreo(),conPro.getSucursal()};
            tabla.addRow(fila);
        }
    }
    
    
    void limpiar() {
        idProv = 0;
        listaDireccionAnexaProv(0);
        listaContactoProveedor(0);
    }
}
